apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rw-users
  namespace: default
subjects:
- kind: ServiceAccount
  name: micze
  namespace: default
roleRef:
  kind: Role
  name: users-rw
  apiGroup: rbac.authorization.k8s.io